#nullable enable
using System.Net.Http;
using System.Threading;
using Cysharp.Threading.Tasks;
using Mochineko.Relent.Resilience;
using Mochineko.Relent.UncertainResult;
using UnityEngine;

namespace Mochineko.Whisper_API.Samples
{
    /// <summary>
    /// A sample component to transcribe speech into text by Whisper transcription API on Unity.
    /// </summary>
    public sealed class TranscriptionSample : MonoBehaviour
    {
        /// <summary>
        /// API key generated by OpenAPI.
        /// </summary>
        [SerializeField]
        private string apiKey = string.Empty;

        /// <summary>
        /// File path of speech audio.
        /// </summary>
        [SerializeField]
        private string filePath = string.Empty;

        private static readonly HttpClient httpClient = new();

        private readonly TranscriptionRequestBody requestBody = new(
            file: string.Empty,
            Model.Whisper1);

        private readonly IPolicy<string> policy = PolicyFactory.Build();

        [ContextMenu(nameof(Transcribe))]
        public void Transcribe()
        {
            TranscribeAsync(this.GetCancellationTokenOnDestroy())
                .Forget();
        }

        private async UniTask TranscribeAsync(CancellationToken cancellationToken)
        {
            requestBody.File = filePath;

            await UniTask.SwitchToThreadPool();

            // Transcribe speech into text by Whisper transcription API.
            var result = await policy
                .ExecuteAsync(async innerCancellationToken
                        => await TranscriptionAPI
                            .TranscribeFromFileAsync(
                                apiKey,
                                httpClient,
                                filePath,
                                requestBody,
                                innerCancellationToken),
                    cancellationToken);

            await UniTask.SwitchToMainThread(cancellationToken);
            
            switch (result)
            {
                // Success
                case IUncertainSuccessResult<string> success:
                {
                    // Default text response format is JSON.
                    var text = TranscriptionResponseBody.FromJson(success.Result)?.Text;
                    // Log text result.
                    Debug.Log($"[Whisper_API.Transcription.Samples] Succeeded to transcribe into: {text}.");
                    break;
                }
                // Retryable failure
                case IUncertainRetryableResult<string> retryable:
                {
                    Debug.LogError($"[Whisper_API.Transcription.Samples] Failed to transcribe because -> {retryable.Message}.");
                    break;
                }
                // Failure
                case IUncertainFailureResult<string> failure:
                {
                    Debug.LogError($"[Whisper_API.Transcription.Samples] Failed to transcribe because -> {failure.Message}.");
                    break;
                }
                default:
                    throw new UncertainResultPatternMatchException(nameof(result));
            }
        }
    }
}