#nullable enable
using System;
using System.Collections.Generic;
using System.IO;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using Newtonsoft.Json;

namespace Mochineko.Whisper_API
{
    /// <summary>
    /// OpenAI Whisper transcription API.
    /// https://platform.openai.com/docs/api-reference/audio/create
    /// </summary>
    public sealed class Transcription
    {
        private const string EndPoint = "https://api.openai.com/v1/audio/transcriptions";

        private readonly IReadOnlyDictionary<string, string> headers;
        private readonly TranscriptionRequestBody requestBody;

        private static HttpClient HttpClient
            => HttpClientPool.PooledClient;

        /// <summary>
        /// Create an instance of Whisper transcription API connection.
        /// </summary>
        /// <param name="apiKey">API key generated by OpenAI</param>
        /// <param name="model">Speech recognition model</param>
        /// <exception cref="ArgumentNullException">API Key must be set</exception>
        public Transcription(string apiKey, Model model = Model.Whisper1)
        {
            if (string.IsNullOrEmpty(apiKey))
            {
                throw new ArgumentNullException(nameof(apiKey));
            }

            this.headers = CreateHeader(apiKey);
            this.requestBody = new TranscriptionRequestBody(string.Empty, model);
        }
        
        /// <summary>
        /// Create an instance of Whisper transcription API connection.
        /// </summary>
        /// <param name="apiKey">API key generated by OpenAI</param>
        /// <param name="requestBody">Request parameters</param>
        /// <exception cref="ArgumentNullException">API Key must be set</exception>
        public Transcription(string apiKey, TranscriptionRequestBody requestBody)
        {
            if (string.IsNullOrEmpty(apiKey))
            {
                throw new ArgumentNullException(nameof(apiKey));
            }

            this.headers = CreateHeader(apiKey);
            this.requestBody = requestBody;
        }
        
        private static IReadOnlyDictionary<string, string> CreateHeader(string apiKey)
            => new Dictionary<string, string>
            {
                ["Authorization"] = $"Bearer {apiKey}",
            };

        private static HttpRequestMessage CreateRequestMessage(
            IReadOnlyDictionary<string, string> headers,
            TranscriptionRequestBody requestBody,
            Stream fileStream)
        {
            var requestMessage = new HttpRequestMessage(HttpMethod.Post, EndPoint);
            foreach (var header in headers)
            {
                requestMessage.Headers.Add(header.Key, header.Value);
            }

            var requestContent = new MultipartFormDataContent();

            requestContent.Add(
                content: new StringContent(
                    content: $"{requestBody.Model}",
                    encoding: System.Text.Encoding.UTF8),
                name: "model");

            requestContent.Add(
                content: new StreamContent(content: fileStream),
                name: "file",
                fileName: requestBody.File);

            requestMessage.Content = requestContent;

            return requestMessage;
        }

        /// <summary>
        /// Transcribes speech audio into text by Whisper transcription API.
        /// </summary>
        /// <param name="filePath"></param>
        /// <param name="cancellationToken"></param>
        /// <returns>Response text</returns>
        /// <exception cref="Exception">System exceptions</exception>
        /// <exception cref="APIErrorException">API error response</exception>
        /// <exception cref="HttpRequestException">Network error</exception>
        /// <exception cref="TaskCanceledException">Cancellation or timeout</exception>
        /// <exception cref="JsonSerializationException">JSON error</exception>
        /// <exception cref="ArgumentNullException">File path is null or empty</exception>
        /// <exception cref="FileNotFoundException">Audio file not found</exception>
        /// <exception cref="InvalidDataException">Not available audio format</exception>
        /// <exception cref="OperationCanceledException">Cancelled on called</exception>
        public async Task<string> TranscribeFromFileAsync(string filePath, CancellationToken cancellationToken)
        {
            cancellationToken.ThrowIfCancellationRequested();

            if (string.IsNullOrEmpty(filePath))
            {
                throw new ArgumentNullException(nameof(filePath));
            }

            if (!File.Exists(filePath))
            {
                throw new FileNotFoundException(filePath);
            }

            if (!TranscriptionRequestBody.IsAvailableFormat(filePath))
            {
                throw new InvalidDataException(filePath);
            }

            await using var stream = File.OpenRead(filePath);

            return await TranscribeAsync(
                fileStream: stream,
                fileName: Path.GetFileName(filePath),
                cancellationToken);
        }

        /// <summary>
        /// Transcribes speech audio into text by Whisper transcription API.
        /// </summary>
        /// <param name="fileStream">File data stream of speech audio</param>
        /// <param name="fileName">File name of speech audio</param>
        /// <param name="cancellationToken">Cancellation token</param>
        /// <returns>Response text.</returns>
        /// <exception cref="Exception">System exceptions</exception>
        /// <exception cref="APIErrorException">API error response</exception>
        /// <exception cref="HttpRequestException">Network error</exception>
        /// <exception cref="TaskCanceledException">Cancellation or timeout</exception>
        /// <exception cref="JsonSerializationException">JSON error</exception>
        /// <exception cref="ArgumentNullException">Argument is null or empty</exception>
        /// <exception cref="InvalidDataException">Not available audio format</exception>
        /// <exception cref="OperationCanceledException">Cancelled on called</exception>
        public async Task<string> TranscribeAsync(
            Stream fileStream,
            string fileName,
            CancellationToken cancellationToken)
        {
            cancellationToken.ThrowIfCancellationRequested();

            if (string.IsNullOrEmpty(fileName))
            {
                throw new ArgumentNullException(nameof(fileName));
            }

            if (!TranscriptionRequestBody.IsAvailableFormat(fileName))
            {
                throw new InvalidDataException(fileName);
            }

            requestBody.File = fileName;

            using var requestMessage = CreateRequestMessage(
                headers,
                requestBody,
                fileStream);

            // Post request and receive response
            using var responseMessage = await HttpClient.SendAsync(requestMessage, cancellationToken);
            if (responseMessage == null)
            {
                throw new Exception($"[Whisper_API.Transcription] HttpResponseMessage is null.");
            }

            var responseText = await responseMessage.Content.ReadAsStringAsync();
            if (string.IsNullOrEmpty(responseText))
            {
                throw new Exception($"[Whisper_API.Transcription] Response JSON is null or empty.");
            }

            if (responseMessage.IsSuccessStatusCode)
            {
                // Text format is determined by request parameter:"response_format".
                return responseText;
            }
            else
            {
                var errorResponseBody = ErrorResponseBody.FromJson(responseText);
                if (errorResponseBody != null)
                {
                    // Handle API error response
                    throw new APIErrorException(responseMessage.StatusCode, errorResponseBody);
                }
                else
                {
                    // Error without error response
                    responseMessage.EnsureSuccessStatusCode();

                    throw new Exception(
                        $"[Whisper_API.Transcription] It should not be be reached with status code:{responseMessage.StatusCode}.");
                }
            }
        }
    }
}